name: IPTV Dokunulmazlık Guncelleme

on:
  schedule:
    - cron: '0 */6 * * *' # Her 6 saatte bir otomatik çalışır
  workflow_dispatch: # Manuel çalıştırma butonu

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Gerekli Paketleri Kur
        run: pip install requests
        
      - name: Dokunulmazlik Süzgecini Çalıştır
        run: python temizle.py # Burası bizim yeni süzgeci tetikler

      - name: Degisiklikleri Kaydet
        run: |
          git config --global user.name "Hüseyin Akçagöz"
          git config --global user.email "action@github.com"
          git add tr.m3u
          git commit -m "♻️ Liste Süzüldü: 2995 Dokunulmaz Kanal Yayında" || exit 0
          git push
