name: IPTV_Guncelleme
on:
  workflow_dispatch: # Manuel calistirma butonu

permissions:
  contents: write

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v3

      - name: Python Hazirla
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Streamlink Yukle
        run: pip install streamlink

      - name: Botu Calistir
        run: python update_list.py

      - name: Kaydet ve Yukle
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "action@github.com"
          git add .
          git commit -m "Kanallar Guncellendi" || exit 0
          git push
