name: IPTV Otomatik Guncelleme

on:
  schedule:
    - cron: '0 0 * * *' # Her gece Turkiye saatiyle 03:00'de calisir
  workflow_dispatch: # Elle baslatma butonu

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v3

      - name: Python Hazirla
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutuphaneleri Kur
        run: pip install requests

      - name: Listeyi Guncelle
        run: python update_list.py

      - name: Kaydet ve Yukle
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add tr.m3u
          git commit -m "Otomatik guncelleme yapildi" || exit 0
          git push
